
language: node_js
node_js:
 — “7”
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project abhinavvishwa-7c06c — token 1/97md-eERVjFpAvvskUNimDVnS1A-DyOl8fBGQmyqQTs